li = [1,5,3]

try:
    li[3] = 2
    print("this line has executed after error thrown")
except:
    pass